
2023-07-11 22:02:58,452 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 22:02:58,453 - aiogram.dispatcher - INFO - Start polling
2023-07-11 22:02:58,633 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 22:03:21,000 - aiogram.event - INFO - Update id=680691238 is not handled. Duration 7438 ms by bot id=6087196605
2023-07-11 22:03:21,000 - aiogram.event - ERROR - Cause exception while process update id=680691238 by bot id=6087196605
TelegramForbiddenError: Telegram server says - Forbidden: bot was blocked by the user
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/middlewares/appshed.py", line 46, in check_and_call
    await bot.send_message(user, text = f"""Привет! Не забудь про сегодняшние задачи!
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/client/bot.py", line 2607, in send_message
    return await self(call, request_timeout=request_timeout)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/client/bot.py", line 400, in __call__
    return await self.session(self, method, timeout=request_timeout)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/client/session/base.py", line 250, in __call__
    return cast(TelegramType, await middleware(bot, method))
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/client/session/aiohttp.py", line 170, in make_request
    response = self.check_response(method=method, status_code=resp.status, content=raw_result)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/client/session/base.py", line 121, in check_response
    raise TelegramForbiddenError(method=method, message=description)
aiogram.exceptions.TelegramForbiddenError: Telegram server says - Forbidden: bot was blocked by the user
2023-07-11 22:05:21,609 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 22:05:21,611 - aiogram.dispatcher - INFO - Start polling
2023-07-11 22:05:21,777 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 22:05:26,193 - aiogram.event - INFO - Update id=680691239 is not handled. Duration 61 ms by bot id=6087196605
2023-07-11 22:05:37,120 - aiogram.event - INFO - Update id=680691240 is handled. Duration 1795 ms by bot id=6087196605
2023-07-11 22:05:45,378 - aiogram.event - INFO - Update id=680691241 is handled. Duration 303 ms by bot id=6087196605
2023-07-11 22:05:48,907 - aiogram.event - INFO - Update id=680691242 is handled. Duration 1019 ms by bot id=6087196605
2023-07-11 22:05:56,675 - aiogram.event - INFO - Update id=680691243 is handled. Duration 1063 ms by bot id=6087196605
2023-07-11 22:05:58,740 - aiogram.event - INFO - Update id=680691244 is not handled. Duration 14 ms by bot id=6087196605
2023-07-11 22:15:35,627 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 22:15:35,628 - aiogram.dispatcher - INFO - Start polling
2023-07-11 22:15:35,794 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 22:15:42,081 - aiogram.event - INFO - Update id=680691245 is not handled. Duration 12 ms by bot id=6087196605
2023-07-11 22:15:50,395 - aiogram.event - INFO - Update id=680691246 is handled. Duration 1884 ms by bot id=6087196605
2023-07-11 22:15:56,345 - aiogram.event - INFO - Update id=680691247 is handled. Duration 215 ms by bot id=6087196605
2023-07-11 22:15:59,633 - aiogram.event - INFO - Update id=680691248 is handled. Duration 221 ms by bot id=6087196605
2023-07-11 22:16:01,988 - aiogram.event - INFO - Update id=680691249 is handled. Duration 223 ms by bot id=6087196605
2023-07-11 22:16:07,167 - aiogram.event - INFO - Update id=680691250 is handled. Duration 217 ms by bot id=6087196605
2023-07-11 22:16:22,133 - aiogram.event - INFO - Update id=680691251 is handled. Duration 875 ms by bot id=6087196605
2023-07-11 22:16:31,737 - aiogram.event - INFO - Update id=680691252 is handled. Duration 864 ms by bot id=6087196605
2023-07-11 22:16:36,003 - aiogram.event - INFO - Update id=680691253 is handled. Duration 220 ms by bot id=6087196605
2023-07-11 22:16:38,858 - aiogram.event - INFO - Update id=680691254 is handled. Duration 1084 ms by bot id=6087196605
2023-07-11 22:16:41,727 - aiogram.event - INFO - Update id=680691255 is handled. Duration 201 ms by bot id=6087196605
2023-07-11 22:16:45,943 - aiogram.event - INFO - Update id=680691256 is handled. Duration 893 ms by bot id=6087196605
2023-07-11 22:16:52,073 - aiogram.event - INFO - Update id=680691257 is handled. Duration 265 ms by bot id=6087196605
2023-07-11 22:17:11,791 - aiogram.event - INFO - Update id=680691258 is handled. Duration 777 ms by bot id=6087196605
2023-07-11 22:17:20,254 - aiogram.event - INFO - Update id=680691259 is handled. Duration 997 ms by bot id=6087196605
2023-07-11 22:17:27,808 - aiogram.event - INFO - Update id=680691260 is handled. Duration 1075 ms by bot id=6087196605
2023-07-11 22:17:37,465 - aiogram.event - INFO - Update id=680691261 is not handled. Duration 12 ms by bot id=6087196605
2023-07-11 22:17:59,060 - aiogram.event - INFO - Update id=680691262 is not handled. Duration 12 ms by bot id=6087196605
2023-07-11 22:18:01,977 - aiogram.event - INFO - Update id=680691263 is not handled. Duration 13 ms by bot id=6087196605
2023-07-11 22:19:25,312 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 22:19:25,314 - aiogram.dispatcher - INFO - Start polling
2023-07-11 22:19:25,499 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 22:19:33,241 - aiogram.event - INFO - Update id=680691264 is handled. Duration 1961 ms by bot id=6087196605
2023-07-11 22:19:38,354 - aiogram.event - INFO - Update id=680691265 is handled. Duration 301 ms by bot id=6087196605
2023-07-11 22:19:40,043 - aiogram.event - INFO - Update id=680691266 is handled. Duration 216 ms by bot id=6087196605
2023-07-11 22:19:45,210 - aiogram.event - INFO - Update id=680691267 is handled. Duration 1632 ms by bot id=6087196605
2023-07-11 22:19:52,878 - aiogram.event - INFO - Update id=680691268 is handled. Duration 213 ms by bot id=6087196605
2023-07-11 22:19:56,040 - aiogram.event - INFO - Update id=680691269 is handled. Duration 880 ms by bot id=6087196605
2023-07-11 22:19:58,233 - aiogram.event - INFO - Update id=680691270 is handled. Duration 878 ms by bot id=6087196605
2023-07-11 22:20:01,138 - aiogram.event - INFO - Update id=680691271 is handled. Duration 203 ms by bot id=6087196605
2023-07-11 22:20:04,048 - aiogram.event - INFO - Update id=680691272 is handled. Duration 300 ms by bot id=6087196605
2023-07-11 22:20:10,765 - aiogram.event - INFO - Update id=680691273 is handled. Duration 230 ms by bot id=6087196605
2023-07-11 22:22:08,074 - aiogram.event - INFO - Update id=680691274 is handled. Duration 563 ms by bot id=6087196605
2023-07-11 22:22:10,249 - aiogram.event - INFO - Update id=680691275 is handled. Duration 861 ms by bot id=6087196605
2023-07-11 22:22:12,296 - aiogram.event - INFO - Update id=680691276 is handled. Duration 866 ms by bot id=6087196605
2023-07-11 22:22:13,699 - aiogram.event - INFO - Update id=680691277 is handled. Duration 211 ms by bot id=6087196605
2023-07-11 22:22:15,891 - aiogram.event - INFO - Update id=680691278 is handled. Duration 945 ms by bot id=6087196605
2023-07-11 22:22:17,289 - aiogram.event - INFO - Update id=680691279 is handled. Duration 220 ms by bot id=6087196605
2023-07-11 22:22:19,999 - aiogram.event - INFO - Update id=680691280 is handled. Duration 881 ms by bot id=6087196605
2023-07-11 22:22:22,139 - aiogram.event - INFO - Update id=680691281 is handled. Duration 885 ms by bot id=6087196605
2023-07-11 22:22:23,895 - aiogram.event - INFO - Update id=680691282 is handled. Duration 228 ms by bot id=6087196605
2023-07-11 22:22:25,966 - aiogram.event - INFO - Update id=680691283 is handled. Duration 1130 ms by bot id=6087196605
2023-07-11 22:22:27,192 - aiogram.event - INFO - Update id=680691284 is handled. Duration 234 ms by bot id=6087196605
2023-07-11 22:22:29,382 - aiogram.event - INFO - Update id=680691285 is handled. Duration 816 ms by bot id=6087196605
2023-07-11 22:22:31,495 - aiogram.event - INFO - Update id=680691286 is handled. Duration 951 ms by bot id=6087196605
2023-07-11 22:22:32,529 - aiogram.event - INFO - Update id=680691287 is handled. Duration 215 ms by bot id=6087196605
2023-07-11 22:22:34,785 - aiogram.event - INFO - Update id=680691288 is handled. Duration 976 ms by bot id=6087196605
2023-07-11 22:22:36,592 - aiogram.event - INFO - Update id=680691289 is handled. Duration 245 ms by bot id=6087196605
2023-07-11 22:22:39,803 - aiogram.event - INFO - Update id=680691290 is handled. Duration 878 ms by bot id=6087196605
2023-07-11 22:22:41,934 - aiogram.event - INFO - Update id=680691291 is handled. Duration 933 ms by bot id=6087196605
2023-07-11 22:22:43,256 - aiogram.event - INFO - Update id=680691292 is handled. Duration 252 ms by bot id=6087196605
2023-07-11 22:22:45,386 - aiogram.event - INFO - Update id=680691293 is handled. Duration 996 ms by bot id=6087196605
2023-07-11 22:22:46,718 - aiogram.event - INFO - Update id=680691294 is handled. Duration 222 ms by bot id=6087196605
2023-07-11 22:22:49,079 - aiogram.event - INFO - Update id=680691295 is handled. Duration 834 ms by bot id=6087196605
2023-07-11 22:22:51,697 - aiogram.event - INFO - Update id=680691296 is handled. Duration 929 ms by bot id=6087196605
2023-07-11 22:22:53,043 - aiogram.event - INFO - Update id=680691297 is handled. Duration 295 ms by bot id=6087196605
2023-07-11 22:22:55,277 - aiogram.event - INFO - Update id=680691298 is handled. Duration 969 ms by bot id=6087196605
2023-07-11 22:22:56,607 - aiogram.event - INFO - Update id=680691299 is handled. Duration 233 ms by bot id=6087196605
2023-07-11 22:22:58,514 - aiogram.event - INFO - Update id=680691300 is handled. Duration 830 ms by bot id=6087196605
2023-07-11 22:23:01,116 - aiogram.event - INFO - Update id=680691301 is handled. Duration 834 ms by bot id=6087196605
2023-07-11 22:23:02,330 - aiogram.event - INFO - Update id=680691302 is handled. Duration 233 ms by bot id=6087196605
2023-07-11 22:23:04,615 - aiogram.event - INFO - Update id=680691303 is handled. Duration 1033 ms by bot id=6087196605
2023-07-11 22:23:06,155 - aiogram.event - INFO - Update id=680691304 is handled. Duration 307 ms by bot id=6087196605
2023-07-11 22:23:08,119 - aiogram.event - INFO - Update id=680691305 is handled. Duration 904 ms by bot id=6087196605
2023-07-11 22:23:10,335 - aiogram.event - INFO - Update id=680691306 is handled. Duration 905 ms by bot id=6087196605
2023-07-11 22:23:11,678 - aiogram.event - INFO - Update id=680691307 is handled. Duration 226 ms by bot id=6087196605
2023-07-11 22:23:14,775 - aiogram.event - INFO - Update id=680691308 is handled. Duration 1144 ms by bot id=6087196605
2023-07-11 22:23:16,172 - aiogram.event - INFO - Update id=680691309 is handled. Duration 232 ms by bot id=6087196605
2023-07-11 22:23:18,389 - aiogram.event - INFO - Update id=680691310 is handled. Duration 928 ms by bot id=6087196605
2023-07-11 22:23:20,284 - aiogram.event - INFO - Update id=680691311 is handled. Duration 885 ms by bot id=6087196605
2023-07-11 22:23:21,727 - aiogram.event - INFO - Update id=680691312 is handled. Duration 293 ms by bot id=6087196605
2023-07-11 22:23:25,059 - aiogram.event - INFO - Update id=680691313 is handled. Duration 995 ms by bot id=6087196605
2023-07-11 22:23:26,529 - aiogram.event - INFO - Update id=680691314 is handled. Duration 408 ms by bot id=6087196605
2023-07-11 22:23:28,860 - aiogram.event - INFO - Update id=680691315 is handled. Duration 832 ms by bot id=6087196605
2023-07-11 22:23:30,529 - aiogram.event - INFO - Update id=680691316 is handled. Duration 905 ms by bot id=6087196605
2023-07-11 22:23:31,638 - aiogram.event - INFO - Update id=680691317 is handled. Duration 280 ms by bot id=6087196605
2023-07-11 22:23:33,777 - aiogram.event - INFO - Update id=680691318 is handled. Duration 983 ms by bot id=6087196605
2023-07-11 22:23:36,470 - aiogram.event - INFO - Update id=680691319 is handled. Duration 213 ms by bot id=6087196605
2023-07-11 22:24:38,555 - aiogram.event - INFO - Update id=680691320 is handled. Duration 1357 ms by bot id=6087196605
2023-07-11 22:24:45,510 - aiogram.event - INFO - Update id=680691321 is not handled. Duration 2 ms by bot id=6087196605
2023-07-11 22:24:45,511 - aiogram.event - ERROR - Cause exception while process update id=680691321 by bot id=6087196605
NameError: name 'is_message' is not defined
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 8, in save_id
    val = (is_message, name)
NameError: name 'is_message' is not defined
2023-07-11 22:26:02,126 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 22:26:02,127 - aiogram.dispatcher - INFO - Start polling
2023-07-11 22:26:02,307 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 22:26:07,800 - aiogram.event - INFO - Update id=680691322 is handled. Duration 1204 ms by bot id=6087196605
2023-07-11 22:26:15,122 - aiogram.event - INFO - Update id=680691323 is not handled. Duration 1 ms by bot id=6087196605
2023-07-11 22:26:15,122 - aiogram.event - ERROR - Cause exception while process update id=680691323 by bot id=6087196605
NameError: name 'id_message' is not defined
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 8, in save_id
    val = (id_message, name)
NameError: name 'id_message' is not defined
2023-07-11 22:26:53,236 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 22:26:53,238 - aiogram.dispatcher - INFO - Start polling
2023-07-11 22:26:53,419 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 22:26:56,884 - aiogram.event - INFO - Update id=680691324 is handled. Duration 1128 ms by bot id=6087196605
2023-07-11 22:27:03,494 - aiogram.event - INFO - Update id=680691325 is not handled. Duration 627 ms by bot id=6087196605
2023-07-11 22:27:03,494 - aiogram.event - ERROR - Cause exception while process update id=680691325 by bot id=6087196605
OperationalError: (1054, "Unknown column 'is_messag' in 'field list'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'is_messag' in 'field list'")
2023-07-11 22:28:24,884 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 22:28:24,885 - aiogram.dispatcher - INFO - Start polling
2023-07-11 22:28:25,055 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 22:28:33,303 - aiogram.event - INFO - Update id=680691326 is handled. Duration 1188 ms by bot id=6087196605
2023-07-11 22:28:41,366 - aiogram.event - INFO - Update id=680691327 is not handled. Duration 633 ms by bot id=6087196605
2023-07-11 22:28:41,366 - aiogram.event - ERROR - Cause exception while process update id=680691327 by bot id=6087196605
OperationalError: (1054, "Unknown column 'is_messag' in 'field list'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'is_messag' in 'field list'")
2023-07-11 22:29:40,152 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 22:29:40,153 - aiogram.dispatcher - INFO - Start polling
2023-07-11 22:29:40,319 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 22:29:48,813 - aiogram.event - INFO - Update id=680691328 is handled. Duration 1194 ms by bot id=6087196605
2023-07-11 22:29:55,347 - aiogram.event - INFO - Update id=680691329 is handled. Duration 1004 ms by bot id=6087196605
2023-07-11 22:30:03,279 - aiogram.event - INFO - Update id=680691330 is handled. Duration 554 ms by bot id=6087196605
2023-07-11 22:30:06,702 - aiogram.event - INFO - Update id=680691331 is handled. Duration 849 ms by bot id=6087196605
2023-07-11 22:30:21,663 - aiogram.event - INFO - Update id=680691332 is handled. Duration 867 ms by bot id=6087196605
2023-07-11 22:30:27,758 - aiogram.event - INFO - Update id=680691333 is handled. Duration 205 ms by bot id=6087196605
2023-07-11 23:27:26,810 - aiogram.dispatcher - ERROR - Failed to fetch updates - TelegramNetworkError: HTTP Client says - Request timeout error
2023-07-11 23:27:26,811 - aiogram.dispatcher - WARNING - Sleep for 1.000000 seconds and try again... (tryings = 0, bot id = 6087196605)
2023-07-11 23:27:28,478 - aiogram.dispatcher - INFO - Connection established (tryings = 1, bot id = 6087196605)
2023-07-11 23:27:28,970 - aiogram.event - INFO - Update id=680691334 is not handled. Duration 490 ms by bot id=6087196605
2023-07-11 23:27:28,970 - aiogram.event - ERROR - Cause exception while process update id=680691334 by bot id=6087196605
ValueError: <Token var=<ContextVar name='instance_Bot' at 0x7f8e70c2c9f0> at 0x7f8e6fb3dec0> was created in a different Context
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 168, in feed_update
    Bot.reset_current(token)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/utils/mixins.py", line 95, in reset_current
    cls.__context_instance.reset(token)
ValueError: <Token var=<ContextVar name='instance_Bot' at 0x7f8e70c2c9f0> at 0x7f8e6fb3dec0> was created in a different Context
2023-07-11 23:27:28,971 - asyncio - ERROR - Task was destroyed but it is pending!
task: <Task pending name='Task-62' coro=<Dispatcher._process_update() done, defined at /home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py:285> wait_for=<Future pending cb=[Task.task_wakeup()]>>
2023-07-11 23:27:30,040 - aiogram.event - INFO - Update id=680691335 is handled. Duration 1559 ms by bot id=6087196605
2023-07-11 23:28:32,612 - aiogram.event - INFO - Update id=680691336 is not handled. Duration 631 ms by bot id=6087196605
2023-07-11 23:28:32,612 - aiogram.event - ERROR - Cause exception while process update id=680691336 by bot id=6087196605
IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
2023-07-11 23:29:19,684 - aiogram.event - INFO - Update id=680691337 is handled. Duration 1292 ms by bot id=6087196605
2023-07-11 23:29:23,447 - aiogram.event - INFO - Update id=680691338 is not handled. Duration 647 ms by bot id=6087196605
2023-07-11 23:29:23,447 - aiogram.event - ERROR - Cause exception while process update id=680691338 by bot id=6087196605
IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
2023-07-11 23:29:28,309 - aiogram.event - INFO - Update id=680691339 is handled. Duration 845 ms by bot id=6087196605
2023-07-11 23:29:34,868 - aiogram.event - INFO - Update id=680691340 is not handled. Duration 634 ms by bot id=6087196605
2023-07-11 23:29:34,868 - aiogram.event - ERROR - Cause exception while process update id=680691340 by bot id=6087196605
IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
2023-07-11 23:33:54,382 - aiogram.event - INFO - Update id=680691341 is handled. Duration 1399 ms by bot id=6087196605
2023-07-11 23:34:02,361 - aiogram.event - INFO - Update id=680691342 is not handled. Duration 651 ms by bot id=6087196605
2023-07-11 23:34:02,362 - aiogram.event - ERROR - Cause exception while process update id=680691342 by bot id=6087196605
IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
2023-07-11 23:44:38,456 - apscheduler.scheduler - INFO - Scheduler started
2023-07-11 23:44:38,458 - aiogram.dispatcher - INFO - Start polling
2023-07-11 23:44:38,629 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-11 23:45:01,204 - aiogram.event - INFO - Update id=680691343 is handled. Duration 1840 ms by bot id=6087196605
2023-07-11 23:51:13,773 - aiogram.event - INFO - Update id=680691344 is handled. Duration 560 ms by bot id=6087196605
2023-07-11 23:51:19,468 - aiogram.event - INFO - Update id=680691345 is handled. Duration 240 ms by bot id=6087196605
2023-07-11 23:51:22,862 - aiogram.event - INFO - Update id=680691346 is handled. Duration 204 ms by bot id=6087196605
2023-07-11 23:58:19,397 - aiogram.event - INFO - Update id=680691347 is handled. Duration 1338 ms by bot id=6087196605
2023-07-11 23:58:23,406 - aiogram.event - INFO - Update id=680691348 is handled. Duration 897 ms by bot id=6087196605
2023-07-11 23:58:26,548 - aiogram.event - INFO - Update id=680691349 is handled. Duration 219 ms by bot id=6087196605
2023-07-12 00:02:42,812 - aiogram.event - INFO - Update id=680691350 is handled. Duration 1186 ms by bot id=6087196605
2023-07-12 00:02:46,695 - aiogram.event - INFO - Update id=680691351 is handled. Duration 1094 ms by bot id=6087196605
2023-07-12 00:02:49,231 - aiogram.event - INFO - Update id=680691352 is handled. Duration 230 ms by bot id=6087196605
2023-07-12 00:02:53,178 - aiogram.event - INFO - Update id=680691353 is handled. Duration 1097 ms by bot id=6087196605
2023-07-12 00:02:58,826 - aiogram.event - INFO - Update id=680691354 is handled. Duration 1063 ms by bot id=6087196605
2023-07-12 00:03:03,285 - aiogram.event - INFO - Update id=680691355 is handled. Duration 248 ms by bot id=6087196605
2023-07-12 00:03:06,236 - aiogram.event - INFO - Update id=680691356 is handled. Duration 920 ms by bot id=6087196605
2023-07-12 00:09:34,461 - aiogram.event - INFO - Update id=680691357 is handled. Duration 1322 ms by bot id=6087196605
2023-07-12 00:09:40,968 - aiogram.event - INFO - Update id=680691358 is not handled. Duration 650 ms by bot id=6087196605
2023-07-12 00:09:40,968 - aiogram.event - ERROR - Cause exception while process update id=680691358 by bot id=6087196605
IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
2023-07-12 00:20:03,715 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 00:20:03,727 - aiogram.dispatcher - INFO - Start polling
2023-07-12 00:20:03,958 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 00:20:59,285 - aiogram.event - INFO - Update id=680691359 is not handled. Duration 657 ms by bot id=6087196605
2023-07-12 00:20:59,285 - aiogram.event - ERROR - Cause exception while process update id=680691359 by bot id=6087196605
OperationalError: (1054, "Unknown column 'id_message' in 'field list'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 24, in cmd_start
    users = await get_id(chat_id)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 44, in get_id
    await cursor.execute(sql, id_message)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'id_message' in 'field list'")
2023-07-12 00:21:06,283 - aiogram.event - INFO - Update id=680691360 is not handled. Duration 671 ms by bot id=6087196605
2023-07-12 00:21:06,284 - aiogram.event - ERROR - Cause exception while process update id=680691360 by bot id=6087196605
OperationalError: (1054, "Unknown column 'id_message' in 'field list'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 24, in cmd_start
    users = await get_id(chat_id)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 44, in get_id
    await cursor.execute(sql, id_message)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.OperationalError: (1054, "Unknown column 'id_message' in 'field list'")
2023-07-12 00:22:32,784 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 00:22:32,785 - aiogram.dispatcher - INFO - Start polling
2023-07-12 00:22:32,952 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 00:22:46,710 - aiogram.event - INFO - Update id=680691361 is not handled. Duration 612 ms by bot id=6087196605
2023-07-12 00:22:46,711 - aiogram.event - ERROR - Cause exception while process update id=680691361 by bot id=6087196605
TypeError: sequence item 0: expected str instance, int found
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 24, in cmd_start
    users = await get_id(chat_id)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 48, in get_id
    r = ''.join(elem)
TypeError: sequence item 0: expected str instance, int found
2023-07-12 00:24:59,959 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 00:24:59,960 - aiogram.dispatcher - INFO - Start polling
2023-07-12 00:25:00,128 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 00:25:01,256 - aiogram.event - INFO - Update id=680691362 is not handled. Duration 655 ms by bot id=6087196605
2023-07-12 00:25:01,256 - aiogram.event - ERROR - Cause exception while process update id=680691362 by bot id=6087196605
TypeError: sequence item 0: expected str instance, int found
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 24, in cmd_start
    users = await get_id(chat_id)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 48, in get_id
    r = ''.join(elem)
TypeError: sequence item 0: expected str instance, int found
2023-07-12 00:26:32,328 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 00:26:32,330 - aiogram.dispatcher - INFO - Start polling
2023-07-12 00:26:32,596 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 00:26:34,249 - aiogram.event - INFO - Update id=680691363 is handled. Duration 1220 ms by bot id=6087196605
2023-07-12 00:27:39,373 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 00:27:39,375 - aiogram.dispatcher - INFO - Start polling
2023-07-12 00:27:39,602 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 00:27:48,450 - aiogram.event - INFO - Update id=680691364 is handled. Duration 5028 ms by bot id=6087196605
2023-07-12 00:28:03,501 - aiogram.event - INFO - Update id=680691365 is handled. Duration 218 ms by bot id=6087196605
2023-07-12 00:28:08,135 - aiogram.event - INFO - Update id=680691366 is handled. Duration 1512 ms by bot id=6087196605
2023-07-12 00:28:39,726 - aiogram.event - INFO - Update id=680691367 is handled. Duration 1167 ms by bot id=6087196605
2023-07-12 00:28:44,029 - aiogram.event - INFO - Update id=680691368 is not handled. Duration 603 ms by bot id=6087196605
2023-07-12 00:28:44,030 - aiogram.event - ERROR - Cause exception while process update id=680691368 by bot id=6087196605
IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 37, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
2023-07-12 00:29:55,113 - aiogram.event - INFO - Update id=680691369 is handled. Duration 2007 ms by bot id=6087196605
2023-07-12 00:34:50,144 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 00:34:50,146 - aiogram.dispatcher - INFO - Start polling
2023-07-12 00:34:50,319 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 00:38:15,972 - aiogram.event - INFO - Update id=680691370 is handled. Duration 566 ms by bot id=6087196605
2023-07-12 00:38:18,521 - aiogram.event - INFO - Update id=680691371 is handled. Duration 922 ms by bot id=6087196605
2023-07-12 00:38:21,906 - aiogram.event - INFO - Update id=680691372 is handled. Duration 205 ms by bot id=6087196605
2023-07-12 00:53:41,619 - aiogram.event - INFO - Update id=680691373 is handled. Duration 4596 ms by bot id=6087196605
2023-07-12 00:53:51,869 - aiogram.event - INFO - Update id=680691374 is not handled. Duration 1521 ms by bot id=6087196605
2023-07-12 00:53:51,870 - aiogram.event - ERROR - Cause exception while process update id=680691374 by bot id=6087196605
IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/start.py", line 42, in process_name
    await save_id(chat_id, name)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_user.py", line 11, in save_id
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1062, "Duplicate entry '2147483647' for key 'users.PRIMARY'")
2023-07-12 01:36:28,377 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 01:36:28,385 - aiogram.dispatcher - INFO - Start polling
2023-07-12 01:36:28,572 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 01:36:53,446 - aiogram.event - INFO - Update id=680691375 is handled. Duration 2251 ms by bot id=6087196605
2023-07-12 01:37:12,061 - aiogram.event - INFO - Update id=680691376 is handled. Duration 3857 ms by bot id=6087196605
2023-07-12 01:37:18,363 - aiogram.event - INFO - Update id=680691377 is handled. Duration 494 ms by bot id=6087196605
2023-07-12 01:37:26,655 - aiogram.event - INFO - Update id=680691378 is handled. Duration 1076 ms by bot id=6087196605
2023-07-12 01:37:29,279 - aiogram.event - INFO - Update id=680691379 is handled. Duration 451 ms by bot id=6087196605
2023-07-12 01:37:31,269 - aiogram.event - INFO - Update id=680691380 is handled. Duration 301 ms by bot id=6087196605
2023-07-12 01:37:34,205 - aiogram.event - INFO - Update id=680691381 is handled. Duration 1769 ms by bot id=6087196605
2023-07-12 01:37:39,175 - aiogram.event - INFO - Update id=680691383 is handled. Duration 697 ms by bot id=6087196605
2023-07-12 01:37:40,155 - aiogram.event - INFO - Update id=680691382 is handled. Duration 2122 ms by bot id=6087196605
2023-07-12 01:37:46,256 - aiogram.event - INFO - Update id=680691384 is handled. Duration 1109 ms by bot id=6087196605
2023-07-12 01:37:49,884 - aiogram.event - INFO - Update id=680691385 is handled. Duration 327 ms by bot id=6087196605
2023-07-12 01:37:55,065 - aiogram.event - INFO - Update id=680691386 is handled. Duration 2756 ms by bot id=6087196605
2023-07-12 01:38:02,473 - aiogram.event - INFO - Update id=680691387 is handled. Duration 1934 ms by bot id=6087196605
2023-07-12 01:38:06,194 - aiogram.event - INFO - Update id=680691389 is handled. Duration 291 ms by bot id=6087196605
2023-07-12 01:38:07,865 - aiogram.event - INFO - Update id=680691388 is handled. Duration 2396 ms by bot id=6087196605
2023-07-12 01:38:12,468 - aiogram.event - INFO - Update id=680691390 is handled. Duration 2449 ms by bot id=6087196605
2023-07-12 01:38:20,931 - aiogram.event - INFO - Update id=680691391 is handled. Duration 880 ms by bot id=6087196605
2023-07-12 01:38:24,663 - aiogram.event - INFO - Update id=680691392 is handled. Duration 210 ms by bot id=6087196605
2023-07-12 01:39:52,838 - aiogram.event - INFO - Update id=680691393 is handled. Duration 970 ms by bot id=6087196605
2023-07-12 01:39:54,627 - aiogram.event - INFO - Update id=680691394 is handled. Duration 222 ms by bot id=6087196605
2023-07-12 01:39:59,349 - aiogram.event - INFO - Update id=680691395 is handled. Duration 3709 ms by bot id=6087196605
2023-07-12 01:40:04,974 - aiogram.event - INFO - Update id=680691396 is handled. Duration 731 ms by bot id=6087196605
2023-07-12 01:40:09,275 - aiogram.event - INFO - Update id=680691397 is handled. Duration 2842 ms by bot id=6087196605
2023-07-12 01:43:11,883 - aiogram.event - INFO - Update id=680691398 is handled. Duration 5759 ms by bot id=6087196605
2023-07-12 01:43:34,187 - aiogram.event - INFO - Update id=680691399 is handled. Duration 803 ms by bot id=6087196605
2023-07-12 01:43:42,487 - aiogram.event - INFO - Update id=680691400 is handled. Duration 3873 ms by bot id=6087196605
2023-07-12 01:43:52,071 - aiogram.event - INFO - Update id=680691401 is handled. Duration 1204 ms by bot id=6087196605
2023-07-12 01:43:56,454 - aiogram.event - INFO - Update id=680691402 is handled. Duration 452 ms by bot id=6087196605
2023-07-12 01:44:06,094 - aiogram.event - INFO - Update id=680691403 is handled. Duration 2526 ms by bot id=6087196605
2023-07-12 01:49:19,193 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 01:49:19,194 - aiogram.dispatcher - INFO - Start polling
2023-07-12 01:49:19,405 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 01:49:25,438 - aiogram.event - INFO - Update id=680691404 is handled. Duration 1536 ms by bot id=6087196605
2023-07-12 01:49:28,302 - aiogram.event - INFO - Update id=680691405 is handled. Duration 275 ms by bot id=6087196605
2023-07-12 01:49:29,770 - aiogram.event - INFO - Update id=680691406 is handled. Duration 248 ms by bot id=6087196605
2023-07-12 01:49:33,132 - aiogram.event - INFO - Update id=680691407 is not handled. Duration 2279 ms by bot id=6087196605
2023-07-12 01:49:33,133 - aiogram.event - ERROR - Cause exception while process update id=680691407 by bot id=6087196605
IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`default_db`.`tasks`, CONSTRAINT `tasks_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id_messag`))')
Traceback (most recent call last):
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in _process_update
    response = await self.feed_update(bot, update, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 147, in feed_update
    response = await self.update.wrap_outer_middleware(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/error.py", line 25, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/middlewares/user_context.py", line 28, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/fsm/middleware.py", line 39, in __call__
    return await handler(event, data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/dispatcher.py", line 265, in _listen_update
    return await self.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 135, in _propagate_event
    response = await router.propagate_event(update_type=update_type, event=event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 116, in propagate_event
    return await observer.wrap_outer_middleware(_wrapped, event=event, data=kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 111, in _wrapped
    return await self._propagate_event(
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/router.py", line 128, in _propagate_event
    response = await observer.trigger(event, **kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/telegram.py", line 124, in trigger
    return await wrapped_inner(event, kwargs)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiogram/dispatcher/event/handler.py", line 42, in call
    return await wrapped()
  File "/home/lee_obsession/TODObot/scripts/handlers/random_catalog/random_hobby.py", line 28, in dat_hobby
    await save_random(task, message.chat.id, data_rand)
  File "/home/lee_obsession/TODObot/scripts/sql/bd_task.py", line 32, in save_random
    await cursor.execute(sql, val)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 239, in execute
    await self._query(query)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/cursors.py", line 457, in _query
    await conn.query(q)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 469, in query
    await self._read_query_result(unbuffered=unbuffered)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 683, in _read_query_result
    await result.read()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 1164, in read
    first_packet = await self.connection._read_packet()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/aiomysql/connection.py", line 652, in _read_packet
    packet.raise_for_error()
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "/home/lee_obsession/TODObot/env/lib/python3.10/site-packages/pymysql/err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.IntegrityError: (1452, 'Cannot add or update a child row: a foreign key constraint fails (`default_db`.`tasks`, CONSTRAINT `tasks_ibfk_1` FOREIGN KEY (`user_id`) REFERENCES `users` (`id_messag`))')
2023-07-12 01:54:57,837 - apscheduler.scheduler - INFO - Scheduler started
2023-07-12 01:54:57,839 - aiogram.dispatcher - INFO - Start polling
2023-07-12 01:54:58,014 - aiogram.dispatcher - INFO - Run polling for bot @FirstLeeObot id=6087196605 - 'RememberBot'
2023-07-12 01:55:02,081 - aiogram.event - INFO - Update id=680691408 is handled. Duration 2973 ms by bot id=6087196605
2023-07-12 01:55:08,181 - aiogram.event - INFO - Update id=680691409 is handled. Duration 241 ms by bot id=6087196605
2023-07-12 01:55:10,742 - aiogram.event - INFO - Update id=680691410 is handled. Duration 363 ms by bot id=6087196605
2023-07-12 01:55:20,203 - aiogram.event - INFO - Update id=680691411 is handled. Duration 3630 ms by bot id=6087196605
2023-07-12 01:57:46,154 - aiogram.event - INFO - Update id=680691412 is handled. Duration 782 ms by bot id=6087196605
2023-07-12 01:57:48,697 - aiogram.event - INFO - Update id=680691413 is handled. Duration 927 ms by bot id=6087196605
2023-07-12 01:57:52,786 - aiogram.event - INFO - Update id=680691414 is handled. Duration 1578 ms by bot id=6087196605
2023-07-12 01:57:57,892 - aiogram.event - INFO - Update id=680691415 is handled. Duration 250 ms by bot id=6087196605
2023-07-12 01:58:01,210 - aiogram.event - INFO - Update id=680691416 is handled. Duration 1606 ms by bot id=6087196605
2023-07-12 01:58:05,572 - aiogram.event - INFO - Update id=680691417 is handled. Duration 382 ms by bot id=6087196605
